name: card_game
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  #provider package
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # card images
  assets:
    - assets/card_back.png
    - assets/king_front.png
    - assets/joker_front.jpg
    - assets/queen_front.png
    - assets/ace_front.png
    - assets/Mr._Krabs.png
    - assets/Plankton_stock_art.webp
    - assets/Patrick_Star.svg.png

    
